### ISSUE TITLE
Improved error handling

### ISSUE THREAD

**Issue by olt** [springmeyer/mapnik-c-api#4]
Hi,
I'd like to discuss how the C-API could improve the current error handling. Right now it just returns false (-1) and prints any exception messages to stdout.

What about adding a `char * error` (or `std::string`?) field to `mapnik_map_t` and `mapnik_image_blob_t`, together with new `mapnik_foo_get_last_error` functions?
All calls to `mapnik_foo_bar` would reset the error and set it to a meaningful message when a new error occurred (e.g. `ex.what()`).

**Comment by fawick** [comment]
I reckon this issue can be closed.
